# Generated by Django 4.0.3 on 2023-03-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_automobilevo_import_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='sale_price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
