# Generated by Django 4.0.3 on 2023-03-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_automobilevo_import_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
