# Generated by Django 4.0.3 on 2023-03-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_serviceappointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='service_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
