# Generated by Django 4.0.3 on 2023-03-07 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_serviceappointment_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='identification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identification', to='service_rest.automobilevo'),
        ),
    ]
